package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Regression Testing")
    void generatedTest() {
        step("Open 'https://stage.onlc.market/'", () -> {
            open("https://stage.onlc.market/");
        });
        step("Поиск по наименованию оферты", () -> {
            $("#HomeOffersForm_query").setValue("Клавиатура DX1").pressEnter().clear();
            sleep(5000);
        });
        step("Нажать на кнопку крестик", () -> {
            $(".anticon-close-circle").click();
        });
        step("Поставщик, наименование", () -> {
            $("#HomeOffersForm_providerQuery").setValue("ООО «Мир Хобби»").pressEnter();
            sleep(9000);
        });
        step("Нажать на кнопку крестик", () -> {
            $(".providerQuery___StyledFormItem-sc-ogeujy-0 .ant-input-suffix").click();
            sleep(6000);
        });

        step("Поставщик, наименование", () -> {
            $("#HomeOffersForm_providerQuery").setValue("1649069856").pressEnter();
            sleep(4000);
        });
        step("Нажать на кнопку крестик", () -> {
            $(".providerQuery___StyledFormItem-sc-ogeujy-0 .ant-input-suffix").click();
            sleep(6000);
        });

        step("Регионы организации", () -> {
            $("#HomeOffersForm_priceFrom").setValue("222");
            sleep(2000);
        });
        step("Регионы организации", () -> {
            $("#HomeOffersForm_priceTo").setValue("222");

        });


        step("Регионы организации", () -> {
            $("#HomeOffersForm_okpd").setValue("02");
            sleep(5000);
        });

    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://stage.onlc.market/'", () ->
            open("https://stage.onlc.market/"));

        step("Page title should have text 'Магазин Малых Закупок'", () -> {
            String expectedTitle = "Магазин Малых Закупок";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://stage.onlc.market/'", () ->
            open("https://stage.onlc.market/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}