package cloud.autotests.tests.role;

import cloud.autotests.tests.TestBase;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Condition.*;
import static com.codeborne.selenide.Selectors.byText;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;

public class UnauthorizedUserTest extends TestBase {
    @Tag("demowebshop")
    @Test
    @Description("Открытие формы авторизации по E-mail ")
    @DisplayName("Regression Testing")
    void openingLoginForm() {

        step("Open 'https://stage.onlc.market/',Открываем любую страницу сайта.", () -> {
            open(url);
            clearBrowserCookies();
            refresh();
            sleep(1000);
        });
    }

    @Tag("demowebshop")
    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://stage.onlc.market/'", () ->
                open(url));

        step("Page title should have text 'Магазин Малых Закупок'", () -> {
            String expectedTitle = "Магазин Малых Закупок";
            String actualTitle = title();
            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Tag("demowebshop")
    @Test
    @Description("Открытие формы авторизации по E-mail ")
    @DisplayName("Regression Testing")
    void openOfferCard() {
        step("Open 'https://stage.onlc.market/", () -> {
            open(url);
            sleep(4000);
        });
        step("Search by offer name", () -> {
            $("#HomeOffersForm_query").setValue("окпд");
        });
        step("Choose an offer", () -> {
            $(".card___StyledTooltipParagraph-sc-eydu8b-5").click();
        });
        step("Check path 'Home' ", () -> {
            $(".ant-breadcrumb-link").shouldHave(text("Главная"));
        });
        step("Check path 'Offer'", () -> {
            $("[href=\"/home/offer/list/\"]").shouldHave(text("Оферты"));
        });
        step("Check path 'Offer name'", () -> {
            $(".breadcrumbs___StyledSpan-sc-nvq3lj-0").shouldHave(text("окпд"));
        });
       step("Name of company", () -> {
            $("[href=\"/home/organisations/1/\"]").shouldHave(text("ООО \"Карта\""));
        });
        step("Imust contain article", () -> {
            $(".key").shouldHave(text("Артикул"));
        });
        step("Сheck article", () -> {
            $("[itemprop='sku']").shouldHave(text("GVXp8FLekA8s"));
        });
        step("Must contain OKPD2", () -> {
            $$(".key").get(1).shouldHave(text("ОКПД2"));
        });
        step("OKPD2 33.2 Point and check the text okpd", () -> {
            $(".popover__Popover-sc-mdy8u9-0").shouldHave(text("33.2")).hover();
            $(".ant-popover-open").shouldHave(text("33.2"));
        });
        step("OKPD2 33.1 Point and check the text okpd", () -> {
            $$(".popover__Popover-sc-mdy8u9-0").get(1).shouldHave(text("33.1")).hover();
            $(".ant-popover-open").shouldHave(text("33.1"));
        });
        step("OKPD2 33 Point and check the text okpd", () -> {
            $$(".popover__Popover-sc-mdy8u9-0").get(2).shouldHave(text("33")).hover();
            $(".ant-popover-open").shouldHave(text("33"));
        });
        step("Must contain publication date", () -> {
            $$(".key").get(2).shouldHave(text("Дата публикации"));
        });
        step("Publication date", () -> {
            $$(".value").get(2).shouldHave(text("18.07.2022"));
        });
        step("Must contain unit of measurement", () -> {
            $$(".key").get(3).shouldHave(text("Ед. измерения"));
        });
        step("unit of measurement", () -> {
            $("[itemprop=\"eligibleQuantity\"]").shouldHave(text("Действующее вещество: Штука"));
        });
        step("Must contain region", () -> {
            $$(".key").get(4).shouldHave(text("Регион"));
        });
        step("Region'", () -> {
            $("[itemprop=\"eligibleRegion\"]").shouldHave(text("Респ Адыгея, Респ Башкортостан"));
        });
        step("Must contain price", () -> {
            $(".id___StyledDiv6-sc-u7v2lr-7").shouldHave(text("45 900,00 руб."));
        });
        step("Must contain НДС", () -> {
            $(".id___StyledDiv7-sc-u7v2lr-10").shouldHave(text("В том числе НДС 10%"));
        });
        step("Unit price comment", () -> {
            $(".id___StyledDiv8-sc-u7v2lr-11").shouldHave(text("Скоро закончится"));
        });
        step("Сontain button add to cart", () -> {
            $(".id___StyledDiv9-sc-u7v2lr-12").shouldHave(text("В КОРЗИНУ"));
            $(byText("В КОРЗИНУ")).click();
            $(".ant-input-number-handler-up").doubleClick();
            sleep(3000);
            $("[role=\"spinbutton\"]").shouldHave(value("3"));
        });
        step("Сheck block download documents", () -> {
            $(".file___StyledSpan-sc-14epk5q-1").shouldBe(visible).click();
            $(".ant-popover").shouldBe(visible);
        });
        step("Получить результат", () -> {
            $("[aria-controls='rc-tabs-0-panel-/home/purchase/list']").shouldHave(text("Закупки")).click();
        });
    }
}
